spring:
  rabbitmq:
    #host: 10.146.0.2
    host: 10.178.0.11
    user: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      host: 10.146.0.4,10.146.0.5,10.146.0.6,10.146.0.7
      port: 9200
